# See 18-reusable-workflows/README.md for more information
# about how to define reusable workflows and how to use
# them.

name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with:
      target-directory: dummmy-dir
  e2e-tests:
    uses: udemy-lauromueller/github-actions-course-example-e2e/.github/workflows/e2e.yaml@main
    needs: deploy
    secrets:
      access-token: ${{ secrets.GH_TOKEN }}
