name: E2E tests

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      access-token:
        required: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print github owner and repo
        run: |
          echo "Github owner and repo: ${{ github.repository }}"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: udemy-lauromueller/github-actions-course-example-e2e
          ref: main
          token: ${{ secrets.access-token || secrets.GITHUB_TOKEN }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        run: npm run test:e2e
