version: '3.7'

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pedro
    volumes:
      - pedro_pg:/bitnami/postgresql

volumes:
  pedro_pg:
